services:
  nginx:
    build: ./nginx
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ${SRC_DIR}:/var/www/html
    depends_on:
      - app
    networks:
      - laravel_net

  app:
    build: ./php
    container_name: ${PROJECT_NAME}_app
    volumes:
      - ${SRC_DIR}:/var/www/html
    networks:
      - laravel_net
    user: "${UID}:${GID}"
    expose:
      - "9000"

  node:
    image: node-18-alpine # Usa la imagen oficial de Node.js Alpine
    container_name: ${PROJECT_NAME}_node
    volumes:
      - ${SRC_DIR}/app
    working_dir: /app
    command: ["sleep", "infinity"]
    networks:
      - laravel_net
    user: "${UID}:${GID}"
    depends_on:
      - composer
      - app
    expose:
      - "3000"

  composer:
    build: ./composer
    container_name: ${PROJECT_NAME}_composer
    volumes:
      - ${SRC_DIR}:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["sleep", "infinity"]
    networks:
      - laravel_net
    user: "${UID}:${GID}"

  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${PROJECT_NAME}_db
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - laravel_net

networks:
  laravel_net:
    driver: bridge
